print_diagnostics: true
reset_on_time_jump: true
two_d_mode: true
odom_frame: odom_ekf
world_frame: odom_ekf
base_link_frame: JA01_base_link
publish_tf: false
frequency: 50

### Vins pose (position only) ###
odom1: /vins_estimator/odometry
odom1_differential: false
odom1_config: [true, true, true,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
